[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "sqlch"
version = "0.1"
requires-python = ">=3.11"

[project.scripts]
sqlch = "sqlch.cli.main:main"

[tool.setuptools.packages.find]
where = ["."]
include = ["sqlch*"]
